University of Michigan - ROB 101 Computational Linear Algebra

# Homework 3: Vector and Matrix Multiplication (12 points)
### Due: 9/26 at 9 PM Eastern

#### Purpose:  Learn ways to compute a matrix multiplication with programming
- Skills: 
    - Indexing for multiplication
    - Converting algorithm to code
    - Lower-Upper factorization without permutations
- Knowledge:
    - Learn how to use built in functions
    - Understand how those functions work behind the scenes

#### Task:  Complete the cells below as directed.

### The Result of a Matrix Multiplication:
$$[n\times k~~\text{matrix}] \cdot [k \times m~~\text{matrix}] = [n \times m~~\text{matrix}].$$

In other words:  In order for the matrix multiplication A times B to be possible, the number of columns in A must equal the number of rows in B.

\begin{equation}
   A \cdot B:= 
\left[\begin{array}{cccc}  a_1^{\rm row} \cdot b_1^{\rm col} & a_1^{\rm row} \cdot b_2^{\rm col} & \cdots & a_1^{\rm row} \cdot b_m^{\rm col} \\
a_2^{\rm row} \cdot b_1^{\rm col} & a_2^{\rm row} \cdot b_2^{\rm col} & \cdots & a_2^{\rm row} \cdot b_m^{\rm col} \\
\vdots & \vdots & \ddots & \vdots \\
a_n^{\rm row} \cdot b_1^{\rm col} & a_n^{\rm row} \cdot b_2^{\rm col} & \cdots & a_n^{\rm row} \cdot b_m^{\rm col}
\end{array}\right].
\end{equation}

### Problem 1.  Rows x Columns (1 + 1 + 1)
Partition the following matrices, then compute the multiplication product using the formula above.

### a) $A*B$ where $A = \begin{bmatrix} 3&7&4\\1&4&3\end{bmatrix}$ and $B = \begin{bmatrix}8&3&9&1\\2&4&0&8\\0&7&1&2\end{bmatrix}$
(1 point)

In [1]:
#declare your partitions first
#leave the values as integers or the check below will return a false answer, even if you are right.
a1row = [3 7 4]
a2row = [1 4 3]
b1col = [8; 2; 0]
b2col = [3; 4; 7]
b3col = [9; 0; 1]
b4col = [1; 8; 2]

#implement code below that forms the matrix A*B by computing each of its individual
#entires via the rows of A times the columns of B 

#your answer should be a 2 x 4 matrix. Return that in a variable called answer1a

answer1a = [a1row * b1col a1row * b2col a1row * b3col a1row * b4col; a2row * b1col a2row * b2col a2row * b3col a2row * b4col]
# your code here


2×4 Matrix{Int64}:
 38  65  31  67
 16  40  12  39

In [2]:
# One of our indirect tests to help you out! 
println("all nothings means likely correct")
T1 = @assert (308 == sum(answer1a))
T2 = @assert (answer1a[1,1] == 38)
[T1 T2]

all nothings means likely correct


1×2 Matrix{Nothing}:
 nothing  nothing

In [3]:
#autograder cell

### b) $C*D$ where $C = \begin{bmatrix} 7&6&8&7&4\\1&8&2&4&3\\6&9&8&1&4\end{bmatrix}$ and $D = \begin{bmatrix}8&3\\0&4\\7&2\\3&8\\9&2\end{bmatrix}$
(1 point)

In [4]:
#Partition C 
c1row = [7 6 8 7 4]
c2row = [1 8 2 4 3]
c3row = [6 9 8 1 4]

#Partition D
d1col = [8; 0; 7; 3; 9]
d2col = [3; 4; 2; 8; 2]

#Compute the matric product and return answer in a variable called answer1b

answer1b = [c1row * d1col c1row * d2col; c2row * d1col c2row *d2col; c3row * d1col c3row * d2col]


3×2 Matrix{Int64}:
 169  125
  61   77
 143   86

In [5]:
println("all nothings means likely correct")
T1 = @assert (661 == sum(answer1b))
T2 = @assert (answer1b[1,1] == 169)
[T1 T2]

all nothings means likely correct


1×2 Matrix{Nothing}:
 nothing  nothing

In [6]:
#autograder cell

### c) Resultant Size Review (1 point)

Access the elements in the 4 corners of the matrix product of C * D using indexing and store them in the variables upperLeft, upperRight, bottomLeft, and bottomRight. We'll work one of them for you.

In [8]:
C = [c1row; c2row; c3row]
D = [8 3; 0 4; 7 2; 3 8; 9 2]
matProduct = C * D

#Your answers here

upperLeft = matProduct[1, 1]
upperRight = matProduct[1, 2]
bottomRight = matProduct[3, 2]
bottomLeft = matProduct[3,1]

# your code here

143

In [9]:
#autograder cell

$$A\cdot B = \sum_{i=1}^{k} a_i^{\rm col} \cdot b_i^{\rm row},  $$
where $k$ is the number of columns in $A$, which must match the number of rows in $B$
### Problem 2.  Summing over Columns and Rows (1 + 2)
Partition the following matrices, then compute the matrix by our second method of matrix multiplication that uses the summation over columns times rows.

### a.  $F*G$ where $F = \begin{bmatrix}5&1&3\\8&2&0\\1&7&6\\8&2&1\end{bmatrix}$ and $G = \begin{bmatrix}2&4\\8&1\\7&0\end{bmatrix}$
(1 point)

In [10]:
#partition F into columns
f1col = [5; 8; 1; 8]
f2col = [1; 2; 7; 2]
f3col = [3; 0; 6; 1]

#partition G into rows
g1row = [2 4]
g2row = [8 1]
g3row = [7 0]

#compute the product by adding up the products of the columns of F times the rows of G.  
#Return your answer as answer2a

# While you can use a for loop here, we not expecting you to do that. 
# Simply adding up three terms is fine!


answer2a = f1col * g1row + f2col * g2row + f3col * g3row



4×2 Matrix{Int64}:
  39  21
  32  34
 100  11
  39  34

In [11]:
# One of our indirect tests to help you out! 
println("all nothings means likely correct")
T1 = @assert (310 == sum(answer2a))
T2 = @assert (39 == answer2a[1,1])
[T1 T2]

all nothings means likely correct


1×2 Matrix{Nothing}:
 nothing  nothing

In [12]:
#autograder cell

### b.  Using the same matrices, F and G, construct a FOR loop to compute the matrix multiplication $F*G$ (2 points)
Remember this formula, and how it works:$$A\cdot B = \sum_{i=1}^{k} a_i^{\rm col} \cdot b_i^{\rm row},  $$
where $k$ is the number of columns in $A$, which must match the number of rows in $B$

Hint: How many times do we have to multiply a column times a row?  What happens to all of the individual column times row matrices at the end?  Keep track of the sum in the for loop so that you don't have to manually sum at the end.

In [15]:
F = [5 1 3; 8 2 0; 1 7 6; 8 2 1]
G = [2 4; 8 1; 7 0]

#Declare a matrix of zeros the size of the matrix product
currentSum = zeros(4,2)
#fill in the number of columns of F (or Rows of G)
n = 3

#the for loop
for i in 1:n
    #use indexing, and the iterator variable(i) to pick out the column and row,
    #then mulitply them together, and update the currentsum
    #Be careful when selecting a row vector! 
    currentSum += F[:, i] * G[i:i, :]
    
end

answer2b = currentSum

4×2 Matrix{Float64}:
  39.0  21.0
  32.0  34.0
 100.0  11.0
  39.0  34.0

In [16]:
#autograder cell
#You should get the same answer that you got in problem 2a
@show answer2b == answer2a

answer2b == answer2a = true


true

### The Trick:  Matrix Multiplication is Already Built into Julia
#### You can simply use the * operator to multiply compatible matrices
What?  I did all that for nothing!  No.  By completing the algorithms above, you have followed along the steps that Julia is taking internally. You now understand the inner workings of the computer!

Note: You still need to implement problems 1 and 2 as directed, otherwise you will receive no points on the assignment.

### Problem 3.  Compute $X*Y$ where $X = \begin{bmatrix}8&5&2&1\\6&1&3&2\end{bmatrix}$ and $Y = \begin{bmatrix}4&4&3\\7&6&5\\0&1&3\\9&8&2\end{bmatrix}$ (1 point)

In [17]:
#Return your answer as answer3
X = [8 5 2 1; 6 1 3 2]
Y = [4 4 3; 7 6 5; 0 1 3; 9 8 2]
answer3 = X * Y


2×3 Matrix{Int64}:
 76  72  57
 49  49  36

In [18]:
# One of our indirect tests to help you out! 
println("all nothings means likely correct")
T1 = @assert (339 == sum(answer3))
T2 = @assert (76 == answer3[1,1])
[T1 T2]

all nothings means likely correct


1×2 Matrix{Nothing}:
 nothing  nothing

In [19]:
#autograder cell

### Problem 4: Zero the rows and columns of a matrix, as taught in lecture (1 point)

#### Example

In [20]:
# Run me don't change me
using Random
using LinearAlgebra
Random.seed!(09162021)
A=randn(4,7)

4×7 Matrix{Float64}:
 -0.415151    2.83404    0.737731  …  -1.07738    -1.10624   -1.2748
 -0.0687448  -0.464602  -0.140971      0.977113   -1.03056    1.00969
 -0.186166   -0.410705  -0.814948      0.672405   -1.62843    0.167308
  1.73483     1.19289   -0.149247      0.0818541   0.384629   0.788431

In [21]:
# Run me don't change me
# Note that something of the size e-16 is numerically equal to zero!!
pivot = A[1,1]
C1=A[:,1]/pivot
R1=A[1:1,:]
Temp=A-C1*R1

4×7 Matrix{Float64}:
 0.0   0.0        0.0        0.0        0.0       0.0        0.0
 0.0  -0.933891  -0.263131   1.06439    1.15552  -0.847381   1.22078
 0.0  -1.68157   -1.14577    0.693582   1.15554  -1.13236    0.738965
 0.0  13.0358     2.93358   -2.19934   -4.4203   -4.2381    -4.53868

#### Your challenge is now to zero the second row and second column of Temp. Call your answer Temp.

In [22]:
# Define pivot, C2, R2 and then compute Temp
pivot = Temp[2,2]
C2= Temp[:,2]/pivot
R2= Temp[2:2,:]
Temp = Temp - C2*R2


4×7 Matrix{Float64}:
 0.0  0.0   0.0        0.0       0.0       0.0        0.0
 0.0  0.0   0.0        0.0       0.0       0.0        0.0
 0.0  0.0  -0.671971  -1.22297  -0.9251    0.393441  -1.45919
 0.0  0.0  -0.739358  12.658    11.709   -16.0663    12.5017

In [ ]:
# One of our indirect tests to help you out! 
println("all nothings means likely correct")
#T1 = @assert (isapprox(-2.9182429724073566, sum(Temp), atol = 1E-9)) #I think this is an issue with the random number generator again
T2 = @assert (isapprox(Temp[2,2], 0, atol = 1E-9))
[T1 T2]

all nothings means likely correct


1×2 Matrix{Nothing}:
 nothing  nothing

In [25]:
#autograder cell


<img src="https://i.postimg.cc/TY79tX04/LUfactorization-No-Permutations.png" width="700">


### Problem 5. LU Factorization Step by Step (1 point)
Follow Algorithm 1 (above), taken from chapter 5 of the course booklet, step by step in Julia, to perform an LU Factorization on Matrix M. Name the lower triangular matrix L and the upper triangular matrix U.
$$ M = \begin{bmatrix}6&5&4\\12&19&14\\24&35&32\end{bmatrix}$$
We are going to do it step by step, just as if you were writing it out as a HW Drill Problem solution. Then, in the next problem, we'll program it up as an honest to goodness algorithm!

In [29]:
L = [0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0]
U = [0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0]
# Do all of your work in this cell
# here, we will NOT test that the pivot is non-zero and just hope for the best!
M = [6 5 4; 12 19 14; 24 35 32]
temp=copy(M)
n,m = size(M)
k=1
C=temp[:,k]
pivot=C[k]
C=C/pivot  # Let's hope we do not divide by zero! Yikes!!! 
L[:,1] = C
R=temp[k,:]' # recall, we have to do the transpose in Julia to get a row vector or we use R=temp[k:k,:]
U[1:1, :] = R

temp = temp-C*R
@show temp
# Run this code now and make sure that temp has a zero first column and a zero first row

# Now its your turn
k=2 #now k will be 2, and we will repeat the steps again for the second column and row
#you will need to repeat this process n times, where n is the number of rows/columns in M

#student code here
C=temp[:,k]
pivot=C[k]
C=C/pivot  # Let's hope we do not divide by zero! Yikes!!! 
L[:,2] = C
R=temp[k,:]' # recall, we have to do the transpose in Julia to get a row vector or we use R=temp[k:k,:]
U[2:2,:] = R
temp = temp-C*R
@show temp

k=3 #now k will be 2, and we will repeat the steps again for the second column and row
#you will need to repeat this process n times, where n is the number of rows/columns in M

#student code here
C=temp[:,k]
pivot=C[k]
C=C/pivot  # Let's hope we do not divide by zero! Yikes!!! 
L[:,3] = C
R=temp[k,:]' # recall, we have to do the transpose in Julia to get a row vector or we use R=temp[k:k,:]
U[3:3,:] = R
temp = temp-C*R
@show temp


#Now return L and U
@show L
@show U

temp = [0.0 0.0 0.0; 0.0 9.0 6.0; 0.0 15.0 16.0]
temp = [0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 6.0]
temp = [0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0]
L = [1.0 0.0 0.0; 2.0 1.0 0.0; 4.0 1.6666666666666667 1.0]
U = [6.0 5.0 4.0; 0.0 9.0 6.0; 0.0 0.0 6.0]


3×3 Matrix{Float64}:
 6.0  5.0  4.0
 0.0  9.0  6.0
 0.0  0.0  6.0

In [30]:
# One of our indirect tests to help you out! 
println("all nothings means likely correct")
T1 = @assert isapprox(abs(sum(L)), 10.666666666666666, atol = 1E-9)
T2 = @assert isapprox(abs(sum(U)), 36, atol = 1E-9)

[T1 T2]

all nothings means likely correct


1×2 Matrix{Nothing}:
 nothing  nothing

In [31]:
#autograder cell

### Problem 6. LU Factorization in Code (2 points)

<img src="https://i.postimg.cc/TY79tX04/LUfactorization-No-Permutations.png" width="700">


Implement Algorithm 1(above), taken from chapter 5 of the course booklet, in code to perform an LU Factorization on Matrix M.
$$ M = \begin{bmatrix}6&5&4\\12&19&14\\24&35&32\end{bmatrix}$$

Remark: When you first implement the algorithm using a for loop, don't worry about checking that the pivot 
is non-zero. Add that at the very end. 

In [33]:
#declare M
M = [6 5 4; 12 19 14; 24 35 32]
#initialization
n,m = size(M)
temp = copy(M)
L = Array{Float64,2}(undef, n, 0)  #~~~\# L=[] Empty matrix\\
U = Array{Float64,2}(undef, 0, n)  #~~~\# R=[] Empty matrix\\
flag = 1
#end initialization

#Your turn! Translate the rest of the algorithm to code here(use a for loop and an if statement)
# your code here
for k in 1:n
    C=Temp[:,k]
    pivot = C[k]
    R = Temp[k,:]'
    if !isapprox(pivot, 0.0, atol = 1E-8)
        C = C/pivot
        Temp = Temp - C*R
        L = [L C]
        U = [U; R]
    else 
        Flag = 0
        println("Matrix requires row permutations")
        println("Step where algorithm failed is k= $k")
        break
    end
end


Matrix requires row permutations
Step where algorithm failed is k= 1


In [34]:
# One of our indirect tests to help you out! 
println("all nothings means likely correct")
T1 = @assert isapprox(abs(sum(L)), 10.666666666666666, atol = 1E-9)
T2 = @assert isapprox(abs(sum(U)), 36, atol = 1E-9)

[T1 T2]

all nothings means likely correct


AssertionError: AssertionError: isapprox(abs(sum(L)), 10.666666666666666, atol = 1.0e-9)

In [ ]:
#autograder cell

#### Congratulations! You just translated an algorithm to code.  This is a key skill for a computer or data scientist.

The good news:  Julia has a built in function that will do the LU factorization for you.  Actually, there are two functions. If we use the LinearAlgebra package, we can find the L and U factors by simply typing:
<br> <br>   (L, U) = lu(M, Val(false))

<br> You can also use factorize(M), but it is not reccomended because this multiple-dispatch-function may return a different type of factorization than an LU. 

Note:  You still need to complete the algorithm above to get points.  It is important that you understand how the algorithm can be done both by hand and by Julia.  Computers exist to make your life easier, but in order for them to do that, you have to understand how they work, and how to use them.

In [35]:
using LinearAlgebra
#LU decomposition without permutations ~Val(false)~
(lower, upper) = lu(M, Val(false))

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0  0.0      0.0
 2.0  1.0      0.0
 4.0  1.66667  1.0
U factor:
3×3 Matrix{Float64}:
 6.0  5.0  4.0
 0.0  9.0  6.0
 0.0  0.0  6.0

In [36]:
#Check that the factorization is correct
lower*upper == M

true

Note: If you leave off the Val(false) argument, lu() will use permutations, and then $L * U \ne M$


For a more in depth explanation about julia's factorization, visit:
https://julia.quantecon.org/tools_and_techniques/numerical_linear_algebra.html

### Problem 7.  Copy your algorithm from problem 5 into the cell below and run your LU Factorization on a 100 x 100 random matrix (1 point)


In [ ]:
N=100
M=rand(N,N)
#copy your algorithm below to return L and U factors of M, a 100 by 100 matrix
# your code here
throw(ErrorException())

In [ ]:
# One of our indirect tests to help you out! 
# Check your answers

println("all nothings means likely correct")
# Check your answer
T1 = @assert isapprox(M, L*U, atol = 1E-9)

# We have not covered norms of matrices and vectors yet in lecture, but
# but you can think of it as a genralized notion of ``length''. 
# Hence, the norm will be small when all of the entries of the matrix are small
# A 100 x 100 matrix has 10,000 entries...a bit much to inspect one by one! 
T2 = @assert isapprox(norm(M-L*U), 0, atol = 1E-9) 

[T1 T2]